const translations = {
    // 1. English
    en: {
        logo: "ENXUA",
        menu_vision: "Vision",
        menu_core: "Identity",
        menu_solutions: "Efficiency",
        menu_impact: "Value",
        menu_global: "Connect",
        login: "Sign in",
        logout: "Logout",
        download_cta: "Download",
        chat_title: "ENXUA Assistant",
        chat_welcome: "Hello! How can we help you with your DX journey today?",
        chat_input: "Type a message...",
        sec1_title_1: "DISCOVER THE",
        sec1_title_2: "UNSEEN",
        sec1_sub: "Perfect AI-driven DX solution, ENXUA",
        vision_title: "Opening New Horizons in the Digital Ecosystem",
        vision_sub: "Our vision is to provide infinite possibilities to humanity through intelligent AI and innovative DX.",
        sec2_title: "Perfect Digital Transformation Solution Built on AI",
        sec2_sub: "Guiding you beyond the complexity of analog into the perfect world of digital code.",
        sec3_title: "Transforming Complex Processes into Intelligent Workflows",
        sec3_sub: "Providing cutting-edge workflows from smart factories to business automation.",
        sec4_title: "Value from Data, Future from Technology",
        sec4_sub: "Unprecedented synergy generated by the combination of human and artificial intelligence.",
        sec5_title: "Experience ENXUA's Intelligent Engine Anywhere in the World",
        sec5_sub: "Supporting cloud-based AI edge computing through global nodes.",
        faq_title: "FAQ & AI Overview",
        q1: "What is ENXUA?",
        a1: "ENXUA is an enterprise AI company providing comprehensive digital transformation (DX) solutions, empowering businesses to transition perfectly into the digital code realm.",
        q2: "What are ENXUA's core capabilities?",
        a2: "We specialize in converting complex analog processes into intelligent digital workflows through smart factories, business automation, and global AI edge computing.",
        q3: "How does ENXUA define the future DX ecosystem?",
        a3: "A seamless global network where human intelligence forms an unprecedented synergy with artificial intelligence to create disruptive value.",
        sec6_title: "Your Next DX Partner, ENXUA",
        sec6_sub: "Contact us now to design the future of your business.",
        contact_us: "Contact Us",
        learn_more: "Learn More",
        form_name: "Name",
        form_email: "Email Address",
        form_msg: "Tell us about your project...",
        form_submit: "Send Inquiry",
        waiting_title: "We are awaiting you.",
        waiting_sub: "Beyond the limits of the digital frontier, together."
    },
    // 2. Korean
    ko: {
        logo: "ENXUA",
        menu_vision: "비전",
        menu_core: "정체성",
        menu_solutions: "효율성",
        menu_impact: "가치",
        menu_global: "연결",
        login: "로그인",
        logout: "로그아웃",
        download_cta: "다운로드",
        chat_title: "ENXUA 어시스턴트",
        chat_welcome: "안녕하세요! ENXUA에 오신 것을 환영합니다. 무엇을 도와드릴까요?",
        chat_input: "메시지를 입력하세요...",
        sec1_title_1: "DISCOVER THE",
        sec1_title_2: "UNSEEN",
        sec1_sub: "AI 기반의 완벽한 디지털 전환 솔루션, ENXUA",
        vision_title: "디지털 생태계의 새로운 지평을 열다",
        vision_sub: "지능형 AI와 혁신적인 DX를 통해 인류에게 무한한 가능성을 제공하는 것이 우리의 비전입니다.",
        sec2_title: "AI 기반의 완벽한 디지털 전환 솔루션",
        sec2_sub: "아날로그의 복잡성을 넘어서 완벽한 디지털 코드의 세계로 안내합니다.",
        sec3_title: "복잡한 공정을 지능형 워크플로우로",
        sec3_sub: "스마트 팩토리부터 비즈니스 자동화까지 최첨단 워크플로우를 제공합니다.",
        sec4_title: "데이터에서 가치를, 기술에서 미래를",
        sec4_sub: "사람과 인공지능이 결합하여 전례 없는 시너지를 생성합니다.",
        sec5_title: "전 세계 어디서나 ENXUA의 지능형 엔진을 만나보세요",
        sec5_sub: "글로벌 노드를 통한 클라우드 기반 인공지능 엣지 컴퓨팅을 지원합니다.",
        faq_title: "FAQ 및 AI 개요",
        q1: "ENXUA는 어떤 기업인가요?",
        a1: "ENXUA는 완벽한 디지털 코드 영역으로의 전환을 돕는 엔터프라이즈 AI 기반 디지털 전환(DX) 종합 솔루션 기업입니다.",
        q2: "ENXUA의 핵심 역량은 무엇인가요?",
        a2: "스마트 팩토리, 비즈니스 자동화, 글로벌 AI 엣지 컴퓨팅을 활용하여 복잡한 아날로그 공정을 지능형 디지털 워크플로우로 전환하는 데 특화되어 있습니다.",
        q3: "ENXUA가 그리는 미래 DX 생태계는?",
        a3: "인간의 지성과 인공지능이 결합해 전례 없는 시너지를 발휘하며, 파괴적인 가치를 창출하는 글로벌 네트워크 생태계입니다.",
        sec6_title: "당신의 다음 DX 파트너, ENXUA",
        sec6_sub: "지금 연락하여 비즈니스의 미래를 디자인하세요.",
        contact_us: "문의하기",
        learn_more: "더 알아보기",
        form_name: "이름",
        form_email: "이메일",
        form_msg: "프로젝트에 대해 알려주세요...",
        form_submit: "문의 보내기",
        waiting_title: "당신을 기다립니다.",
        waiting_sub: "함께 디지털의 한계를 넘어서."
    },
    // 3. Spanish
    es: {
        logo: "ENXUA",
        menu_vision: "Visión",
        menu_core: "Identidad",
        menu_solutions: "Eficiencia",
        menu_impact: "Valor",
        menu_global: "Conectar",
        login: "Iniciar sesión",
        logout: "Cerrar sesión",
        download_cta: "Descargar",
        chat_title: "Asistente ENXUA",
        chat_welcome: "¡Hola! ¿Cómo podemos ayudarte en tu viaje DX hoy?",
        chat_input: "Escribe un mensaje...",
        sec1_title_1: "DISCOVER THE",
        sec1_title_2: "UNSEEN",
        sec1_sub: "La solución perfecta de DX basada en IA, ENXUA",
        vision_title: "Abriendo Nuevos Horizontes en el Ecosistema Digital",
        vision_sub: "Nuestra visión es brindar posibilidades infinitas a la humanidad a través de IA inteligente y DX innovadora.",
        sec2_title: "La Solución Perfecta de Transformación Digital Construida con IA",
        sec2_sub: "Guiándote más allá de la complejidad analógica hacia el mundo perfecto del código digital.",
        sec3_title: "Transformando Procesos Complejos en Flujos de Trabajo Inteligentes",
        sec3_sub: "Ofreciendo flujos de trabajo de vanguardia desde fábricas inteligentes hasta automatización empresarial.",
        sec4_title: "Valor desde los Datos, Futuro desde la Tecnología",
        sec4_sub: "Una sinergia sin precedentes generada por la combinación de inteligencia humana y artificial.",
        sec5_title: "Experimenta el Motor Inteligente de ENXUA en Cualquier Parte del Mundo",
        sec5_sub: "Soportando computación perimetral de IA basada en la nube a través de nodos globales.",
        faq_title: "Preguntas Frecuentes y Resumen de IA",
        q1: "¿Qué es ENXUA?",
        a1: "ENXUA es una empresa de IA empresarial que proporciona soluciones integrales de transformación digital (DX), capacitando a las empresas para hacer una transición perfecta al ámbito del código digital.",
        q2: "¿Cuáles son las capacidades centrales de ENXUA?",
        a2: "Nos especializamos en convertir procesos analógicos complejos en flujos de trabajo digitales inteligentes a través de fábricas inteligentes, automatización empresarial y computación de borde de IA global.",
        q3: "¿Cómo define ENXUA el futuro ecosistema DX?",
        a3: "Una red global fluida donde la inteligencia humana forma una sinergia sin precedentes con la inteligencia artificial para crear valor disruptivo.",
        sec6_title: "Tu Próximo Socio DX, ENXUA",
        sec6_sub: "Contáctanos ahora para diseñar el futuro de tu negocio.",
        contact_us: "Contáctanos",
        learn_more: "Más Información",
        form_name: "Nombre",
        form_email: "Correo Electrónico",
        form_msg: "Cuéntanos sobre tu proyecto...",
        form_submit: "Enviar Consulta",
        waiting_title: "Te estamos esperando.",
        waiting_sub: "Más allá de los límites de la frontera digital, juntos."
    },
    // 4. French
    fr: {
        logo: "ENXUA",
        menu_vision: "Vision",
        menu_core: "Identité",
        menu_solutions: "Efficacité",
        menu_impact: "Valeur",
        menu_global: "Connecter",
        login: "Se connecter",
        logout: "Se déconnecter",
        download_cta: "Télécharger",
        chat_title: "Assistant ENXUA",
        chat_welcome: "Bonjour ! Comment pouvons-nous vous aider dans votre parcours DX aujourd'hui ?",
        chat_input: "Tapez un message...",
        sec1_title_1: "DISCOVER THE",
        sec1_title_2: "UNSEEN",
        sec1_sub: "La solution DX parfaite basée sur l'IA, ENXUA",
        vision_title: "Ouvrir de Nouveaux Horizons dans l'Écosystème Numérique",
        vision_sub: "Notre vision est d'offrir des possibilités infinies à l'humanité grâce à une IA intelligente et une DX innovante.",
        sec2_title: "La Solution Parfaite de Transformation Numérique Construite sur l'IA",
        sec2_sub: "Vous guider au-delà de la complexité analogique dans le monde parfait du code numérique.",
        sec3_title: "Transformer des Processus Complexes en Flux de Travail Intelligents",
        sec3_sub: "Fournir des flux de travail de pointe, des usines intelligentes à l'automatisation des entreprises.",
        sec4_title: "La Valeur par les Données, l'Avenir par la Technologie",
        sec4_sub: "Une synergie sans précédent générée par la combinaison de l'intelligence humaine et artificielle.",
        sec5_title: "Découvrez le Moteur Intelligent d'ENXUA Partout dans le Monde",
        sec5_sub: "Soutenir l'informatique de pointe IA basée sur le cloud via des nœuds globaux.",
        faq_title: "FAQ & Aperçu IA",
        q1: "Qu'est-ce qu'ENXUA ?",
        a1: "ENXUA est une société d'IA d'entreprise offrant des solutions complètes de transformation numérique (DX), permettant aux entreprises de passer parfaitement au domaine du code numérique.",
        q2: "Quelles sont les capacités clés d'ENXUA ?",
        a2: "Nous sommes spécialisés dans la conversion de processus analogiques complexes en flux de travail numériques intelligents via des usines intelligentes, l'automatisation globale des affaires et l'IA en périphérie de réseau.",
        q3: "Comment ENXUA définit-il l'écosystème DX futur ?",
        a3: "Un réseau mondial transparent où l'intelligence humaine forme une synergie sans précédent avec l'intelligence artificielle pour créer une valeur perturbatrice.",
        sec6_title: "Votre Prochain Partenaire DX, ENXUA",
        sec6_sub: "Contactez-nous maintenant pour concevoir l'avenir de votre entreprise.",
        contact_us: "Nous Contacter",
        learn_more: "En Savoir Plus",
        form_name: "Nom",
        form_email: "Adresse Email",
        form_msg: "Parlez-nous de votre projet...",
        form_submit: "Envoyer une demande",
        waiting_title: "Nous vous attendons.",
        waiting_sub: "Au-delà des limites de la frontière numérique, ensemble."
    },
    // 5. Italian
    it: {
        logo: "ENXUA",
        menu_vision: "Visione",
        menu_core: "Identità",
        menu_solutions: "Efficienza",
        menu_impact: "Valore",
        menu_global: "Connetti",
        login: "Accedi",
        logout: "Esci",
        download_cta: "Scarica",
        chat_title: "Assistente ENXUA",
        chat_welcome: "Ciao! Come possiamo aiutarti oggi nel tuo viaggio DX?",
        chat_input: "Scrivi un messaggio...",
        sec1_title_1: "DISCOVER THE",
        sec1_title_2: "UNSEEN",
        sec1_sub: "La soluzione DX perfetta basata sull'intelligenza artificiale, ENXUA",
        vision_title: "Aprire Nuovi Orizzonti nell'Ecosistema Digitale",
        vision_sub: "La nostra visione è fornire infinite possibilità all'umanità attraverso IA intelligente e DX innovativa.",
        sec2_title: "La Perfetta Soluzione di Trasformazione Digitale Basata sull'IA",
        sec2_sub: "Guidarvi oltre la complessità analogica nel mondo perfetto del codice digitale.",
        sec3_title: "Trasformare Processi Complessi in Flussi di Lavoro Intelligenti",
        sec3_sub: "Fornire flussi di lavoro all'avanguardia, dalle fabbriche intelligenti all'automazione aziendale.",
        sec4_title: "Valore dai Dati, Futuro dalla Tecnologia",
        sec4_sub: "Una sinergia senza precedenti generata dalla combinazione di intelligenza umana e artificiale.",
        sec5_title: "Sperimenta il Motore Intelligente di ENXUA Ovunque nel Mondo",
        sec5_sub: "Supporto del computing edge IA basato su cloud attraverso nodi globali.",
        faq_title: "FAQ & Panoramica IA",
        q1: "Che cos'è ENXUA?",
        a1: "ENXUA è un'azienda di intelligenza artificiale aziendale che fornisce soluzioni complete di trasformazione digitale (DX), consentendo alle aziende di passare perfettamente nel regno del codice digitale.",
        q2: "Quali sono le capacità principali di ENXUA?",
        a2: "Siamo specializzati nella conversione di complessi processi analogici in flussi di lavoro digitali intelligenti attraverso fabbriche intelligenti, automazione aziendale e calcolo globale ai margini dell'IA.",
        q3: "Come definisce ENXUA il futuro ecosistema DX?",
        a3: "Una rete globale senza interruzioni in cui l'intelligenza umana forma una sinergia senza precedenti con l'intelligenza artificiale per creare un valore dirompente.",
        sec6_title: "Il Tuo Prossimo Partner DX, ENXUA",
        sec6_sub: "Contattaci ora per progettare il futuro della tua azienda.",
        contact_us: "Contattaci",
        learn_more: "Scopri di Più",
        form_name: "Nome",
        form_email: "Indirizzo Email",
        form_msg: "Parlaci del tuo progetto...",
        form_submit: "Invia Richiesta",
        waiting_title: "Ti stiamo aspettando.",
        waiting_sub: "Insieme, oltre i limiti della frontiera digitale."
    },
    // 6. Portuguese
    pt: {
        logo: "ENXUA",
        menu_vision: "Visão",
        menu_core: "Identidade",
        menu_solutions: "Eficiência",
        menu_impact: "Valor",
        menu_global: "Conectar",
        login: "Entrar",
        logout: "Sair",
        download_cta: "Baixar",
        chat_title: "Assistente ENXUA",
        chat_welcome: "Olá! Como podemos ajudar na sua jornada DX hoje?",
        chat_input: "Digite uma mensagem...",
        sec1_title_1: "DISCOVER THE",
        sec1_title_2: "UNSEEN",
        sec1_sub: "A solução DX perfeita impulsionada por IA, ENXUA",
        vision_title: "Abrindo Novos Horizontes no Ecossistema Digital",
        vision_sub: "Nossa visão é fornecer infinitas possibilidades à humanidade através de IA inteligente e DX inovadora.",
        sec2_title: "A Perfeita Solução de Transformação Digital Baseada em IA",
        sec2_sub: "Guiando você além da complexidade analógica para o mundo perfeito do código digital.",
        sec3_title: "Transformando Processos Complexos em Fluxos de Trabalho Inteligentes",
        sec3_sub: "Fornecendo fluxos de trabalho de ponta, desde fábricas inteligentes até automação de negócios.",
        sec4_title: "Valor através dos Dados, Futuro através da Tecnologia",
        sec4_sub: "Sinergia sem precedentes gerada pela combinação de inteligência humana e artificial.",
        sec5_title: "Experimente o Motor Inteligente da ENXUA em Qualquer Lugar do Mundo",
        sec5_sub: "Suportando computação de borda de IA baseada em nuvem através de nós globais.",
        faq_title: "FAQ & Visão Geral da IA",
        q1: "O que é ENXUA?",
        a1: "ENXUA é uma empresa de inteligência artificial corporativa que fornece soluções abrangentes de transformação digital (DX), capacitando empresas a transitar perfeitamente para o reino do código digital.",
        q2: "Quais são as principais capacidades da ENXUA?",
        a2: "Somos especialistas em converter processos analógicos complexos em fluxos de trabalho digitais inteligentes por meio de fábricas inteligentes, automação de negócios e computação de borda de IA global.",
        q3: "Como a ENXUA define o futuro ecossistema DX?",
        a3: "Uma rede global unificada onde a inteligência humana forma uma sinergia sem precedentes com a inteligência artificial para criar um valor disruptivo.",
        sec6_title: "Seu Próximo Parceiro DX, ENXUA",
        sec6_sub: "Contate-nos agora para desenhar o futuro do seu negócio.",
        contact_us: "Contate-nos",
        learn_more: "Saiba Mais",
        form_name: "Nome",
        form_email: "E-mail",
        form_msg: "Conte-nos sobre o seu projeto...",
        form_submit: "Enviar Consulta",
        waiting_title: "Estamos esperando por você.",
        waiting_sub: "Além dos limites da fronteira digital, juntos."
    },
    // 7. Japanese
    ja: {
        logo: "ENXUA",
        menu_vision: "ビジョン",
        menu_core: "アイデンティティ",
        menu_solutions: "効率",
        menu_impact: "価値",
        menu_global: "接続",
        login: "ログイン",
        logout: "ログアウト",
        download_cta: "ダウンロード",
        chat_title: "ENXUA アシスタント",
        chat_welcome: "こんにちは！今日のDXの旅をどのようにお手伝いしましょうか？",
        chat_input: "メッセージを入力...",
        sec1_title_1: "DISCOVER THE",
        sec1_title_2: "UNSEEN",
        sec1_sub: "AI主導の完璧なDXソリューション、ENXUA",
        vision_title: "デジタルエコシステムの新たな地平を切り拓く",
        vision_sub: "私たちのビジョンは、インテリジェントなAIと革新的なDXを通じて人類に無限の可能性を提供することです。",
        sec2_title: "AIに基づいて構築された完璧なデジタルトランスフォーメーション",
        sec2_sub: "アナログの複雑さを超えて、完璧なデジタルコードの世界へ導きます。",
        sec3_title: "複雑なプロセスをインテリジェントなワークフローへ",
        sec3_sub: "スマートファクトリーからビジネスの自動化まで、最先端のワークフローを提供します。",
        sec4_title: "データから価値を、テクノロジーから未来を",
        sec4_sub: "人間と人工知能の結合によって生み出される前例のない相乗効果。",
        sec5_title: "世界中どこでもENXUAのインテリジェントエンジンを体験",
        sec5_sub: "グローバルノードを通じてクラウドベースのAIエッジコンピューティングをサポートします。",
        faq_title: "よくある質問 / AI 概要",
        q1: "ENXUAとは何ですか？",
        a1: "ENXUAは、包括的なデジタルトランスフォーメーション(DX)ソリューションを提供するエンタープライズAI企業であり、ビジネスがデジタルコードの領域へと完全に移行するのを支援します。",
        q2: "ENXUAの主要な強みは何ですか？",
        a2: "複雑なアナログプロセスを、スマートファクトリー、ビジネスの自動化、グローバルなAIエッジコンピューティングを通じて、インテリジェントなデジタルワークフローに変換することを専門としています。",
        q3: "ENXUAは将来のDXエコシステムをどのように定義していますか？",
        a3: "人間の知性とAIが前例のない相乗効果を形成し、破壊的な価値を創造する、シームレスなグローバルネットワークです。",
        sec6_title: "あなたの次のDXパートナー、ENXUA",
        sec6_sub: "ビジネスの未来をデザインするために今すぐご連絡ください。",
        contact_us: "お問い合わせ",
        learn_more: "詳細はこちら",
        form_name: "名前",
        form_email: "メールアドレス",
        form_msg: "プロジェクトについて教えてください...",
        form_submit: "お問い合わせを送信",
        waiting_title: "あなたをお待ちしています。",
        waiting_sub: "共にデジタルフロンティアの限界を超えて。"
    },
    // 8. Simplified Chinese
    "zh-CN": {
        logo: "ENXUA",
        menu_vision: "愿景",
        menu_core: "特性",
        menu_solutions: "效率",
        menu_impact: "价值",
        menu_global: "连接",
        login: "登录",
        logout: "登出",
        download_cta: "下载",
        chat_title: "ENXUA 助手",
        chat_welcome: "您好！今天我们在您的数字化转型旅程中能提供什么帮助？",
        chat_input: "输入消息...",
        sec1_title_1: "DISCOVER THE",
        sec1_title_2: "UNSEEN",
        sec1_sub: "完美的AI驱动的DX解决方案, ENXUA",
        vision_title: "开创数字生态系统的新纪元",
        vision_sub: "我们的愿景是通过智能人工智能和创新的数字化转型，为人类提供无限可能。",
        sec2_title: "基于AI的完美数字化转型解决方案",
        sec2_sub: "引导您超越模拟信号的复杂性，进入完美的数字代码世界。",
        sec3_title: "将复杂流程转变为智能工作流",
        sec3_sub: "从智能工厂到业务自动化，提供尖端的工作流程。",
        sec4_title: "数据创造价值，技术创造未来",
        sec4_sub: "人类与人工智能的结合产生了前所未有的协同效应。",
        sec5_title: "在全球各地体验ENXUA的智能引擎",
        sec5_sub: "通过全球节点支持基于云的AI边缘计算。",
        faq_title: "常见问题及AI概述",
        q1: "ENXUA 是什么？",
        a1: "ENXUA 是一家企业级 AI 公司，提供全面的数字化转型 (DX) 解决方案，帮助企业完美过渡到数字代码领域。",
        q2: "ENXUA 的核心能力是什么？",
        a2: "我们专注于通过智能工厂、业务自动化和全球 AI 边缘计算，将复杂的模拟过程转换为智能数字工作流。",
        q3: "ENXUA 如何定义未来的 DX 生态系统？",
        a3: "一个无缝的全球网络，人类智能与人工智能形成前所未有的协同效应，创造颠覆性价值。",
        sec6_title: "您下一个数字化转型合作伙伴，ENXUA",
        sec6_sub: "立即联系我们，设计您的业务未来。",
        contact_us: "联系我们",
        learn_more: "了解更多",
        form_name: "姓名",
        form_email: "电子邮件",
        form_msg: "请告诉我们您的项目...",
        form_submit: "发送咨询",
        waiting_title: "我们期待您的加入。",
        waiting_sub: "携手超越自我的数字边界。"
    },
    // 9. Traditional Chinese
    "zh-TW": {
        logo: "ENXUA",
        menu_vision: "願景",
        menu_core: "特性",
        menu_solutions: "效率",
        menu_impact: "價值",
        menu_global: "連接",
        login: "登入",
        logout: "登出",
        download_cta: "下載",
        chat_title: "ENXUA 助手",
        chat_welcome: "您好！今天我們在您的數位化轉型旅程中能提供什麼幫助？",
        chat_input: "輸入訊息...",
        sec1_title_1: "DISCOVER THE",
        sec1_title_2: "UNSEEN",
        sec1_sub: "完美的AI驅動的DX解決方案, ENXUA",
        vision_title: "開創數位生態系統的新紀元",
        vision_sub: "我們的願景是透過智慧人工智慧和創新的數位化轉型，為人類提供無限可能。",
        sec2_title: "基於AI的完美數位化轉型解決方案",
        sec2_sub: "引導您超越類比訊號的複雜性，進入完美的數位程式碼世界。",
        sec3_title: "將複雜流程轉變為智能工作流",
        sec3_sub: "從智能工廠到業務自動化，提供尖端的工作流程。",
        sec4_title: "資料創造價值，技術創造未來",
        sec4_sub: "人類與人工智慧的結合產生了前所未有的協同效應。",
        sec5_title: "在全球各地體驗ENXUA的智能引擎",
        sec5_sub: "透過全球節點支援基於雲端的AI邊緣運算。",
        faq_title: "常見問題及AI概述",
        q1: "ENXUA 是什麼？",
        a1: "ENXUA 是一家企業級 AI 公司，提供全面的數位轉型 (DX) 解決方案，幫助企業完美過渡到數位代碼領域。",
        q2: "ENXUA 的核心能力是什麼？",
        a2: "我們專注於透過智能工廠、業務自動化和全球 AI 邊緣運算，將複雜的模擬過程轉換為智能數位工作流。",
        q3: "ENXUA 如何定義未來的 DX 生態系統？",
        a3: "一個無縫的全球網路，人類智能與人工智慧形成前所未有的協同效應，創造顛覆性價值。",
        sec6_title: "您下一個數位化轉型合作夥伴，ENXUA",
        sec6_sub: "立即聯絡我們，設計您的業務未來。",
        contact_us: "聯絡我們",
        learn_more: "了解更多",
        form_name: "姓名",
        form_email: "電子郵件",
        form_msg: "請告訴我們您的專案...",
        form_submit: "發送諮詢",
        waiting_title: "我們期待您的加入。",
        waiting_sub: "攜手超越自我的數字邊界。"
    }
};

function initI18n() {
    const langSwitchBtns = document.querySelectorAll('[data-lang]');
    const currentLangBtn = document.getElementById('current-lang');

    // Full label map (desktop)
    const langDisplayMap = {
        'en': '🇺🇸 English',
        'es': '🇪🇸 Español',
        'fr': '🇫🇷 Français',
        'it': '🇮🇹 Italiano',
        'pt': '🇵🇹 Português',
        'ko': '🇰🇷 한국어',
        'ja': '🇯🇵 日本語',
        'zh-CN': '🇨🇳 简体中文',
        'zh-TW': '🇭🇰 繁體中文'
    };

    // Short label map (mobile ≤768px)
    const langShortMap = {
        'en': 'EN',
        'es': 'ES',
        'fr': 'FR',
        'it': 'IT',
        'pt': 'PT',
        'ko': 'KR',
        'ja': 'JP',
        'zh-CN': 'CN',
        'zh-TW': 'TW'
    };

    // Returns correct label depending on screen width
    const getLangLabel = (lang) => {
        return window.innerWidth <= 768
            ? (langShortMap[lang] || 'EN')
            : (langDisplayMap[lang] || langDisplayMap['en']);
    };

    // Update button label on resize too
    window.addEventListener('resize', () => {
        const saved = localStorage.getItem('enxua_lang') || 'en';
        currentLangBtn.textContent = getLangLabel(saved);
    });

    const setLanguage = (lang) => {
        // Fallback to en if unsupported
        const finalLang = translations[lang] ? lang : 'en';
        const t = translations[finalLang];

        // Update tags containing text - using innerHTML to support basic semantic HTML injected safely via i18n
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (t[key]) {
                el.innerHTML = t[key]; // Changed to innerHTML to allow tags if needed
            }
        });

        // Update attribute placeholders
        document.querySelectorAll('[data-i18n-attr]').forEach(el => {
            const info = el.getAttribute('data-i18n-attr').split('=');
            if (info.length === 2 && t[info[1]]) {
                el.setAttribute(info[0], t[info[1]]);
            }
        });

        // Update Dropdown Button Text — short on mobile, full on desktop
        currentLangBtn.textContent = getLangLabel(finalLang);

        // Persist the choice to localStorage overrides the system settings on the next visit
        try {
            localStorage.setItem('enxua_lang', finalLang);
        } catch (e) {
            console.error("Local storage error:", e);
        }
    };

    // Initialization Logic (LocalStorage -> System Language -> English)
    let initialLang = 'en';

    try {
        const savedLang = localStorage.getItem('enxua_lang');
        if (savedLang && translations[savedLang]) {
            initialLang = savedLang;
        } else {
            // No saved language, try detecting from system browser
            const userLang = navigator.language || navigator.userLanguage; // e.g., 'ko-KR', 'fr-FR', 'pt-BR'

            if (userLang.startsWith('ko')) initialLang = 'ko';
            else if (userLang.startsWith('es')) initialLang = 'es';
            else if (userLang.startsWith('fr')) initialLang = 'fr';
            else if (userLang.startsWith('it')) initialLang = 'it';
            else if (userLang.startsWith('pt')) initialLang = 'pt';
            else if (userLang.startsWith('ja')) initialLang = 'ja';
            else if (userLang === 'zh-CN' || userLang === 'zh-SG' || userLang.startsWith('zh-Hans')) initialLang = 'zh-CN';
            else if (userLang.startsWith('zh')) initialLang = 'zh-TW';
        }
    } catch (e) {
        initialLang = 'en';
    }

    setLanguage(initialLang);

    // Event listeners
    langSwitchBtns.forEach(btn => {
        btn.addEventListener('click', (e) => {
            e.preventDefault();
            const lang = e.target.getAttribute('data-lang');
            setLanguage(lang);
        });
    });
}
